{
    'name': 'Lab management',
    'version': '1.0',
    'summary': 'Professional Lab & Radiology Management System',
    'description': 'A complete Odoo 17 module for managing medical labs and radiology centers.',
    'category': 'Healthcare',
    'author': 'Rehab',
    'website': 'https://yourwebsite.com',
    'license': 'LGPL-3',
    'depends': ['base', 'product', 'account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/patient_views.xml',
        'views/doctor_views.xml',
        'views/lab_test_views.xml',
        'views/radiology_views.xml',
        'views/invoice_views.xml',
        'report/lab_test_report.xml',
        'report/radiology_report.xml',
        # 'report/invoice_report.xml',
        # 'data/lab_test_data.xml',
        # 'data/radiology_data.xml',
        # 'data/product_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
