{
    'name': 'Real Estate & Construction Management',
    'version': '1.0',
    'category': 'Real Estate',
    'summary': 'Complete Real Estate and Construction Management System',
    'author': 'Rehab',
    'depends': ['base', 'account', 'hr', 'stock', 'sale', 'purchase'],
    'data': [
        'security/ir.model.access.csv',
        'views/property_view.xml',
        'views/unit_view.xml',
        'views/customer_view.xml',
        'views/contract_views.xml',
        'views/project_view.xml',
        'views/subcontractor_views.xml',
        'views/inventory_views.xml',
        'views/accounting_views.xml',
        'views/hr_views.xml',
        'views/equipment_views.xml',
        # 'views/reporting_dashboard.xml',
        # 'data/sequence_data.xml',
    ],
    'installable': True,
    'application': True,
}